[package]
name = "plugin_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
plugin_runtime = { path = "../plugin-runtime" }
syn = "1.0"
quote = "1.0"
darling = "0.14.1"